In [153]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [154]:
data = pd.read_csv("Diabetes_dataset.csv")

In [155]:
x = data.iloc[:,:-1].values
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [156]:
y = data.iloc[:,-1].values
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [157]:
# le = LabelEncoder()
# y = le.fit_transform(y)
# y

In [158]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
print("Training Set", x_train)
print("Testing Set", x_test)

Training Set [[  2.    139.     75.    ...  25.6     0.167  29.   ]
 [  3.    124.     80.    ...  33.2     0.305  26.   ]
 [  2.    112.     66.    ...  25.      0.307  24.   ]
 ...
 [  4.    127.     88.    ...  34.5     0.598  28.   ]
 [  1.     99.     58.    ...  25.4     0.551  21.   ]
 [  9.    154.     78.    ...  30.9     0.164  45.   ]]
Testing Set [[ 13.     76.     60.    ...  32.8     0.18   41.   ]
 [  9.    112.     82.    ...  28.2     1.282  50.   ]
 [  0.    105.     84.    ...  27.9     0.741  62.   ]
 ...
 [  9.    120.     72.    ...  20.8     0.733  48.   ]
 [ 10.    129.     76.    ...  35.9     0.28   39.   ]
 [  5.     73.     60.    ...  26.8     0.268  27.   ]]


In [159]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
x_train

array([[-0.56609199,  0.53112303,  0.29172565, ..., -0.87359291,
        -0.91317756, -0.38635016],
       [-0.26722657,  0.06342601,  0.54761072, ...,  0.1235535 ,
        -0.49003766, -0.63799691],
       [-0.56609199, -0.3107316 , -0.16886748, ..., -0.952315  ,
        -0.4839052 , -0.8057614 ],
       ...,
       [ 0.03163885,  0.15696542,  0.95702683, ...,  0.29411802,
         0.40836805, -0.47023241],
       [-0.86495741, -0.71606902, -0.57828359, ..., -0.89983361,
         0.26425519, -1.05740815],
       [ 1.52596594,  0.99882005,  0.44525669, ..., -0.17821449,
        -0.92237625,  0.95576582]])

In [160]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))
ann.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))
ann.compile(optimizer="adam", loss="binary_crossentropy", metrics=['accuracy'])

In [161]:
ann.fit(x_train, y_train, batch_size=5, epochs=100)

Epoch 1/100
123/123 [==============================] - 1s 1ms/step - loss: 0.6380 - accuracy: 0.6450
Epoch 2/100
123/123 [==============================] - 0s 1ms/step - loss: 0.6007 - accuracy: 0.6466
Epoch 3/100
123/123 [==============================] - 0s 1ms/step - loss: 0.5723 - accuracy: 0.6694
Epoch 4/100
123/123 [==============================] - 0s 1ms/step - loss: 0.5501 - accuracy: 0.6889
Epoch 5/100
123/123 [==============================] - 0s 1ms/step - loss: 0.5360 - accuracy: 0.6954
Epoch 6/100
123/123 [==============================] - 0s 1ms/step - loss: 0.5262 - accuracy: 0.7085
Epoch 7/100
123/123 [==============================] - 0s 1ms/step - loss: 0.5164 - accuracy: 0.7166
Epoch 8/100
123/123 [==============================] - 0s 1ms/step - loss: 0.5105 - accuracy: 0.7199
Epoch 9/100
123/123 [==============================] - 0s 1ms/step - loss: 0.5036 - accuracy: 0.7378
Epoch 10/100
123/123 [==============================] - 0s 1ms/step - loss: 0.4981 - accura

In [162]:
# x_test
predicted = ann.predict(x_test)
pred = list(map(lambda predicted: 1 if predicted >= 0.5 else 0, predicted))
print("Predicted Values: ", predicted)
print("Predicted Values in Binary: ", pred)
print("Actual Values: ", y_test)
print("Accuracy: ", accuracy_score(y_test, pred))

5/5 [==============================] - 0s 2ms/step
Predicted Values:  [[3.14930528e-01]
 [4.05803740e-01]
 [2.91026503e-01]
 [2.90991738e-02]
 [1.19555190e-01]
 [3.66834134e-01]
 [3.43134452e-04]
 [1.24062635e-02]
 [6.24524474e-01]
 [1.80710271e-01]
 [9.42547545e-02]
 [5.72224140e-01]
 [9.54316139e-01]
 [2.38710502e-03]
 [7.79488802e-01]
 [3.07401389e-01]
 [1.25286222e-01]
 [4.43649232e-01]
 [3.19457442e-01]
 [9.76642296e-02]
 [4.68801893e-02]
 [8.07498991e-02]
 [4.01641905e-01]
 [4.15513292e-02]
 [9.69657660e-01]
 [8.18707108e-01]
 [1.89810060e-02]
 [4.51411337e-01]
 [2.13403124e-04]
 [6.77655578e-01]
 [3.32547754e-01]
 [6.81919456e-02]
 [5.32193363e-01]
 [3.37789595e-01]
 [7.49152005e-01]
 [7.01277912e-01]
 [8.20255697e-01]
 [3.63453090e-01]
 [5.59095740e-01]
 [7.35951126e-01]
 [1.17248639e-01]
 [6.46908104e-01]
 [8.82035017e-01]
 [8.51390719e-01]
 [6.01624727e-01]
 [7.76630491e-02]
 [1.56131133e-01]
 [1.07945241e-01]
 [1.27334287e-02]
 [1.80752680e-01]
 [8.92197907e-01]
 [1.98460996